<<<<<<< HEAD
# Generated by Django 3.1.3 on 2020-11-29 05:16
=======
# Generated by Django 3.1.3 on 2020-11-26 20:10
>>>>>>> 8a93aa023d3093268e39e5586e1342c29b6de194

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
<<<<<<< HEAD
                ('ssn', models.CharField(max_length=10, primary_key=True, serialize=False)),
=======
                ('Ssn', models.CharField(max_length=10, primary_key=True, serialize=False)),
>>>>>>> 8a93aa023d3093268e39e5586e1342c29b6de194
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
<<<<<<< HEAD
                ('contract_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('money', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
=======
                ('Contract_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Money', models.IntegerField()),
                ('Start_date', models.DateTimeField()),
                ('End_date', models.DateTimeField()),
>>>>>>> 8a93aa023d3093268e39e5586e1342c29b6de194
            ],
        ),
        migrations.CreateModel(
            name='License_Type',
            fields=[
<<<<<<< HEAD
                ('type', models.CharField(max_length=10, primary_key=True, serialize=False)),
=======
                ('Type', models.CharField(max_length=10, primary_key=True, serialize=False)),
>>>>>>> 8a93aa023d3093268e39e5586e1342c29b6de194
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('name', models.CharField(max_length=100)),
                ('home_country', models.CharField(max_length=100)),
                ('year_founded', models.IntegerField()),
=======
                ('Name', models.CharField(max_length=100)),
                ('Home_country', models.CharField(max_length=100)),
                ('Year_founded', models.IntegerField()),
>>>>>>> 8a93aa023d3093268e39e5586e1342c29b6de194
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
<<<<<<< HEAD
                ('admin_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.client')),
=======
                ('Admin_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.client')),
>>>>>>> 8a93aa023d3093268e39e5586e1342c29b6de194
            ],
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('admin_manager', models.CharField(max_length=10)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.client')),
=======
                ('Admin_manager', models.CharField(max_length=10)),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.client')),
>>>>>>> 8a93aa023d3093268e39e5586e1342c29b6de194
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
<<<<<<< HEAD
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
=======
                ('Username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=50)),
>>>>>>> 8a93aa023d3093268e39e5586e1342c29b6de194
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_Type',
            fields=[
<<<<<<< HEAD
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('default_img', models.URLField(blank=True, default=None, null=True)),
                ('license_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.license_type')),
                ('manufacturer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.manufacturer')),
=======
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Model', models.CharField(max_length=100)),
                ('License_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.license_type')),
                ('Manufacturer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.manufacturer')),
>>>>>>> 8a93aa023d3093268e39e5586e1342c29b6de194
            ],
        ),
        migrations.CreateModel(
            name='Watercraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('max_speed', models.IntegerField()),
                ('length', models.IntegerField()),
                ('capacity', models.CharField(max_length=100)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.vehicle_type')),
=======
                ('Max_speed', models.IntegerField()),
                ('Length', models.IntegerField()),
                ('Capacity', models.CharField(max_length=100)),
                ('Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.vehicle_type')),
>>>>>>> 8a93aa023d3093268e39e5586e1342c29b6de194
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_Instance',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.IntegerField()),
                ('preview_image_paths', models.URLField()),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.vehicle_type')),
            ],
            options={
                'unique_together': {('serial_no', 'type_id')},
            },
=======
                ('Serial_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Preview_image_paths', models.CharField(max_length=120)),
                ('Type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.vehicle_type')),
            ],
>>>>>>> 8a93aa023d3093268e39e5586e1342c29b6de194
        ),
        migrations.CreateModel(
            name='Spacecraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('max_weight', models.IntegerField()),
                ('max_thrust', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=100)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.vehicle_type')),
=======
                ('Max_weight', models.IntegerField()),
                ('Max_thrust', models.CharField(max_length=100)),
                ('Fuel_type', models.CharField(max_length=100)),
                ('Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.vehicle_type')),
>>>>>>> 8a93aa023d3093268e39e5586e1342c29b6de194
            ],
        ),
        migrations.CreateModel(
            name='Rents_Out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('daily_rate', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.partner')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.vehicle_instance')),
=======
                ('Daily_rate', models.IntegerField()),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.partner')),
                ('Vserial_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vserial_no_ro', to='swankyDB.vehicle_instance')),
                ('Vtype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.vehicle_instance')),
>>>>>>> 8a93aa023d3093268e39e5586e1342c29b6de194
            ],
        ),
        migrations.CreateModel(
            name='Rents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('contract_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.contract')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.renter')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.vehicle_instance')),
=======
                ('Contract_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.contract')),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.renter')),
                ('Vserial_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vserial_no_r', to='swankyDB.vehicle_instance')),
                ('Vtype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.vehicle_instance')),
>>>>>>> 8a93aa023d3093268e39e5586e1342c29b6de194
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('name', models.CharField(max_length=50)),
                ('ssn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.client')),
=======
                ('Name', models.CharField(max_length=50)),
                ('Ssn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.client')),
>>>>>>> 8a93aa023d3093268e39e5586e1342c29b6de194
            ],
        ),
        migrations.CreateModel(
            name='Made_Spaceship_Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('part_name', models.CharField(max_length=100)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.manufacturer')),
                ('spacecraft_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.spacecraft')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('license_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.renter')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.license_type')),
=======
                ('Part_name', models.CharField(max_length=100)),
                ('Manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.manufacturer')),
                ('Spacecraft_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.spacecraft')),
            ],
        ),
        migrations.CreateModel(
            name='License_Inst',
            fields=[
                ('License_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.renter')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.license_type')),
>>>>>>> 8a93aa023d3093268e39e5586e1342c29b6de194
            ],
        ),
        migrations.CreateModel(
            name='Land_Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('max_speed', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=100)),
                ('horsepower', models.IntegerField()),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.vehicle_type')),
=======
                ('Max_speed', models.IntegerField()),
                ('Fuel_type', models.CharField(max_length=100)),
                ('Horsepower', models.IntegerField()),
                ('Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.vehicle_type')),
>>>>>>> 8a93aa023d3093268e39e5586e1342c29b6de194
            ],
        ),
        migrations.AddField(
            model_name='client',
<<<<<<< HEAD
            name='username',
=======
            name='Username',
>>>>>>> 8a93aa023d3093268e39e5586e1342c29b6de194
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.user'),
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('engine_count', models.IntegerField()),
                ('takeoff_speed', models.IntegerField()),
                ('seat_count', models.IntegerField()),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.vehicle_type')),
=======
                ('Engine_count', models.IntegerField()),
                ('Takeoff_speed', models.IntegerField()),
                ('Seat_count', models.IntegerField()),
                ('Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.vehicle_type')),
>>>>>>> 8a93aa023d3093268e39e5586e1342c29b6de194
            ],
        ),
        migrations.CreateModel(
            name='Admin_User',
            fields=[
<<<<<<< HEAD
                ('admin_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.user')),
=======
                ('Admin_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swankyDB.user')),
>>>>>>> 8a93aa023d3093268e39e5586e1342c29b6de194
            ],
        ),
    ]
