# Generated by Django 3.1.3 on 2020-11-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swankyDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacecraft',
            name='max_thrust',
            field=models.IntegerField(),
        ),
    ]
