# Generated by Django 3.1.3 on 2020-11-30 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swankyDB', '0002_auto_20201129_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partner',
            name='admin_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swankyDB.admin_user'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='admin_manager',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swankyDB.admin_user'),
        ),
    ]
